<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3E1AtDA\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3E1AtDA/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container3E1AtDA.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container3E1AtDA\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container3E1AtDA\appAppKernelProdContainer([
    'container.build_hash' => '3E1AtDA',
    'container.build_id' => 'd689de84',
    'container.build_time' => 1719924319,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3E1AtDA');
