<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZbFbYj\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZbFbYj/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerMZbFbYj.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerMZbFbYj\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerMZbFbYj\appAppKernelProdContainer([
    'container.build_hash' => 'MZbFbYj',
    'container.build_id' => 'c2f8bcc3',
    'container.build_time' => 1719478614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZbFbYj');
